# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [ ]:
#Creating sample array
arr = np.arange(0,11)

### Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [ ]:
#Get a value at an index
arr[8]

8

In [ ]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

___
## Broadcasting

NumPy arrays differ from normal Python lists because of their ability to broadcast. With lists, you can only reassign parts of a list with new parts of the same size and shape. That is, if you wanted to replace the first 5 elements in a list with a new value, you would have to pass in a new 5 element list. With NumPy arrays, you can broadcast a single value across a larger set of values:

In [ ]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Important notes on Slices
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
#Change Slice
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

___
## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend using the comma notation for clarity.

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [ ]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [ ]:
# Getting individual element value
arr_2d[1,0]

20

In [ ]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [ ]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

___
## Conditional Selection

This is a very fundamental concept that will directly translate to pandas later on, make sure you understand this part!

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr>4

In [ ]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])